import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import ClientProvider from "./ClientProvider";
import dynamic from "next/dynamic";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Simply Good Foods",
  description: "Generated by create next app",
};

const ClientProvider = dynamic(() => import('./ClientProvider'), { ssr: false })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
      <ClientProvider>
        {children}
      </ClientProvider>
      </body>
    </html>
  );
}
